version: "3.8"

services:
  backend:
    image: docker.io/jtp001/hihaho-dashboard-backend:latest
    env_file:
      - .env
    depends_on:
      - frontend
    ports:
      - "8000"

  frontend:
    image: docker.io/jtp001/hihaho-dashboard-frontend:latest
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "80"
